export interface Competitor {
  slug: string;
  name: string;
  shortName: string;
  appStoreRating: string;
  annualPrice: string;
  hasAds: boolean;
  freeAds: boolean;
  tuningCount: string;
  bilingual: boolean;
  description: string;
  mainComplaint: string;
  gtAdvantage: string;
  faqs: { q: string; a: string }[];
}

export interface Tuning {
  slug: string;
  name: string;
  shorthand: string;
  strings: string[];
  notes: string[];
  genre: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  description: string;
  howTo: string[];
  commonSongs: string[];
  isPremium: boolean;
  faqs: { q: string; a: string }[];
}

export const COMPETITORS: Competitor[] = [
  {
    slug: "guitartuna",
    name: "GuitarTuna",
    shortName: "GuitarTuna",
    appStoreRating: "4.8",
    annualPrice: "$47.99/yr",
    hasAds: true,
    freeAds: true,
    tuningCount: "50+",
    bilingual: true,
    description: "GuitarTuna is the market-leading guitar tuner app with over 50 million downloads. It offers a large library of tunings and a metronome but monetizes heavily through ads in the free tier — showing full-screen ads every 30 seconds, including during active tuning sessions.",
    mainComplaint: "Aggressive ads that appear every 30 seconds — even while you're in the middle of tuning a string. Users on Reddit (r/guitar) consistently cite this as their main pain point.",
    gtAdvantage: "GuitarTune never shows ads during tuning — not even in the free tier. Same pitch accuracy, same core tunings, 78% cheaper for Pro ($9.99/yr vs $47.99/yr).",
    faqs: [
      { q: "Does GuitarTuna have ads?", a: "Yes. GuitarTuna's free tier shows full-screen ads approximately every 30 seconds, including while you're actively tuning strings. Removing ads requires GuitarTuna Premium at $47.99/year." },
      { q: "What is a good GuitarTuna alternative with no ads?", a: "GuitarTune is a direct GuitarTuna alternative with zero ads — even on the free tier. It offers the same pitch accuracy, Drop D, Open G, DADGAD and more tunings, and Pro costs $9.99/year (78% cheaper)." },
      { q: "Is GuitarTuna free?", a: "GuitarTuna has a free tier but it shows ads frequently during use. To remove ads you need GuitarTuna Premium ($47.99/year or $3.99/month)." },
      { q: "How does GuitarTune compare to GuitarTuna?", a: "Both apps use real-time pitch detection for guitar tuning. GuitarTune's key differences: no ads ever (including free tier), $9.99/year vs $47.99/year for Pro, bilingual English/Spanish, tuning history, and Solana Pay support." },
    ],
  },
  {
    slug: "fender-tune",
    name: "Fender Tune",
    shortName: "Fender Tune",
    appStoreRating: "4.7",
    annualPrice: "$35.99/yr",
    hasAds: false,
    freeAds: false,
    tuningCount: "22",
    bilingual: true,
    description: "Fender Tune is the official tuner from Fender Musical Instruments, designed primarily for beginners and Fender guitar owners. It integrates with Fender Play lessons and has a clean UI, but its free tier locks most alternate tunings behind a paywall and focuses heavily on upselling Fender Play subscriptions.",
    mainComplaint: "Heavy upselling to Fender Play ($9.99/mo) and limited free tunings. The app feels like a funnel for the Fender ecosystem rather than a standalone tuning tool.",
    gtAdvantage: "GuitarTune is a standalone tuner with no ecosystem lock-in. More free tunings (3 free alternates vs Fender Tune's standard-only free), cheaper Pro ($9.99/yr vs $35.99/yr), and bilingual without requiring a Fender account.",
    faqs: [
      { q: "Is Fender Tune free?", a: "Fender Tune has a free tier for standard tuning but most alternate tunings and features require Fender Play ($9.99/month) or Fender Tone+ Pro ($35.99/year)." },
      { q: "What's better: Fender Tune or GuitarTune?", a: "For standalone tuning, GuitarTune offers more free tunings, no upsells, no ecosystem lock-in, and cheaper Pro pricing ($9.99/yr vs $35.99/yr). Fender Tune is better if you're already in the Fender Play ecosystem." },
      { q: "Does Fender Tune have Drop D?", a: "Yes, but Drop D is locked behind Fender Pro in Fender Tune. In GuitarTune, Drop D is a Pro feature at $9.99/year — less than a third of Fender's price." },
    ],
  },
  {
    slug: "boss-tuner",
    name: "Boss Tuner",
    shortName: "Boss",
    appStoreRating: "4.5",
    annualPrice: "$29.99 one-time",
    hasAds: false,
    freeAds: false,
    tuningCount: "10",
    bilingual: false,
    description: "Boss Tuner is the official app from Boss (Roland Corporation), a legendary name in guitar effects pedals. It's targeted at experienced musicians and offers a clean, pedal-style UI. It's a paid-only app (one-time purchase) with no free tier, which means zero ads — but also zero trial.",
    mainComplaint: "No free tier — requires upfront payment with no trial. English-only. Limited tuning selection. No ongoing development updates. The UI mimics hardware pedals but can feel dated.",
    gtAdvantage: "GuitarTune has a fully functional free tier (no payment required to start), bilingual EN/ES, tuning history, and custom themes in Pro. The $9.99/year Pro is also cheaper than Boss Tuner's $29.99 one-time fee in value terms over 3+ years.",
    faqs: [
      { q: "Is Boss Tuner free?", a: "No. Boss Tuner requires a one-time purchase (approximately $29.99) with no free tier. GuitarTune is free to download with a fully functional ad-free tuner, no payment required." },
      { q: "Boss Tuner vs GuitarTune — which is better?", a: "Both are ad-free tuners. GuitarTune is free to start, has more tunings, is bilingual, and offers tuning history. Boss Tuner has a strong hardware-inspired UI and Boss brand credibility. For value, GuitarTune wins." },
      { q: "Does Boss Tuner work for alternate tunings?", a: "Boss Tuner supports a limited set of tunings. GuitarTune supports 15 tunings including Drop D, DADGAD, Open G, and Nashville in Pro, plus tuning history and custom themes." },
    ],
  },
  {
    slug: "pano-tuner",
    name: "Pano Tuner",
    shortName: "Pano",
    appStoreRating: "4.7",
    annualPrice: "$19.99 one-time",
    hasAds: false,
    freeAds: false,
    tuningCount: "Chromatic only",
    bilingual: false,
    description: "Pano Tuner is a well-regarded chromatic tuner known for its accuracy and clean design. Unlike guitar-specific tuners, it's a universal chromatic tuner — it tunes any instrument but has no guitar-specific presets, string selectors, or alternate tuning libraries.",
    mainComplaint: "Not guitar-specific — no string selector, no alternate tuning presets, no Drop D or DADGAD. Works as a chromatic reference but requires the user to know their target note. English-only.",
    gtAdvantage: "GuitarTune is designed specifically for guitarists with a string selector, 10 named guitar tuning presets, and a guitar-oriented dial UI. Pano Tuner is better for multi-instrument use; GuitarTune is better for guitarists who want a guitar-first experience.",
    faqs: [
      { q: "Is Pano Tuner good for guitar?", a: "Pano Tuner is accurate for chromatic tuning but has no guitar-specific features like tuning presets, string selectors, or alternate tuning libraries. GuitarTune is built specifically for guitar with 10 named tunings, a string selector, and cents-accuracy display." },
      { q: "Pano Tuner vs GuitarTune — which should I use?", a: "If you play multiple instruments, Pano Tuner's chromatic approach works across all of them. If you're primarily a guitarist — especially one who uses alternate tunings like Drop D or Open G — GuitarTune is the better choice." },
      { q: "Does Pano Tuner have Drop D?", a: "No. Pano Tuner is chromatic — you tune to any note manually. GuitarTune has Drop D as a named preset (Pro tier, $9.99/year) where all 6 strings are pre-configured for Drop D tuning." },
    ],
  },
  {
    slug: "chromatic-guitar-tuner",
    name: "Chromatic Guitar Tuner",
    shortName: "Chromatic Tuner",
    appStoreRating: "4.3",
    annualPrice: "Free (ads)",
    hasAds: true,
    freeAds: true,
    tuningCount: "6",
    bilingual: false,
    description: "Various generic 'Chromatic Guitar Tuner' apps exist across the App Store and Google Play, typically built by small developers with heavy ad monetization. They offer basic tuning functionality but suffer from poor UI, aggressive ads, and infrequent updates.",
    mainComplaint: "Heavy ad load, poor UI design, infrequent updates, and inconsistent accuracy. Many are abandoned apps with no active development.",
    gtAdvantage: "GuitarTune is actively maintained, has a professional UI, no ads in the free tier, and offers genuine technical features (autocorrelation engine, cents readout, tuning history) that generic tuner apps lack.",
    faqs: [
      { q: "Are free chromatic guitar tuner apps accurate?", a: "Accuracy varies. Many free chromatic tuner apps use basic pitch detection that can be inconsistent. GuitarTune uses autocorrelation-based pitch detection, the same algorithm used in professional tuning software, accurate to ±1 cent." },
      { q: "What is the best free guitar tuner app with no ads?", a: "GuitarTune offers a free guitar tuner with zero ads — not reduced ads, but literally no ads. Standard tuning plus three alternate tunings (Double Drop D, Open C, All Fourths) are free forever." },
    ],
  },
  {
    slug: "guitar-tuna-pro",
    name: "GuitarTuna Pro",
    shortName: "GuitarTuna Pro",
    appStoreRating: "4.8",
    annualPrice: "$47.99/yr",
    hasAds: false,
    freeAds: false,
    tuningCount: "50+",
    bilingual: true,
    description: "GuitarTuna Pro is the paid tier of GuitarTuna that removes ads and unlocks the full tuning library. While it delivers a genuinely good product, the price ($47.99/year) is the primary friction point — more than 4x the cost of GuitarTune Pro.",
    mainComplaint: "High price point. At $47.99/year, GuitarTuna Pro is one of the most expensive tuner subscriptions available, competing unfavorably against GuitarTune's $9.99/year for core functionality.",
    gtAdvantage: "GuitarTune Pro at $9.99/year delivers the same core accuracy, 15 tunings, tuning history, and bilingual support at 79% of the price savings. For players who only need guitar tuning (not the full GuitarTuna ecosystem), GuitarTune Pro is the smarter value.",
    faqs: [
      { q: "Is GuitarTuna Pro worth it?", a: "GuitarTuna Pro removes ads and unlocks 50+ tunings for $47.99/year. If you need a large tuning library or use other GuitarTuna features, it may be worth it. If you just need accurate guitar tuning with alternate tunings, GuitarTune Pro ($9.99/year) delivers the same core value at 79% less." },
      { q: "What does GuitarTuna Pro include?", a: "GuitarTuna Pro includes ad-free tuning, 50+ tunings, a chord library, and scale trainer. GuitarTune Pro ($9.99/yr) includes ad-free tuning, 15 guitar-specific tunings, tuning history, and custom themes — focused purely on the tuning experience." },
    ],
  },
  {
    slug: "ultimate-guitar-tuner",
    name: "Ultimate Guitar Tuner",
    shortName: "UG Tuner",
    appStoreRating: "4.5",
    annualPrice: "Part of UG subscription ($49.99/yr)",
    hasAds: true,
    freeAds: true,
    tuningCount: "Standard + common alternates",
    bilingual: false,
    description: "Ultimate Guitar's built-in tuner is part of the Ultimate Guitar tabs and chords platform. It's functional but primarily designed as a feature within the UG ecosystem rather than a standalone tuner. Access to the tuner without ads requires an Ultimate Guitar Pro subscription.",
    mainComplaint: "Not a standalone app — requires the full UG ecosystem. UG Pro is $49.99/year for tabs + tuner + metronome. Excessive for users who just need a tuner.",
    gtAdvantage: "GuitarTune is a dedicated tuner app. If you just need a tuner (not tabs or chord libraries), GuitarTune Pro at $9.99/year is purpose-built and nearly 80% cheaper than UG Pro.",
    faqs: [
      { q: "Does Ultimate Guitar have a free tuner?", a: "Yes, Ultimate Guitar includes a tuner but it shows ads in the free tier. Removing ads requires Ultimate Guitar Pro ($49.99/year), which is designed for tab and chord access — not just tuning." },
      { q: "Ultimate Guitar tuner vs GuitarTune — which is better?", a: "For pure tuning, GuitarTune wins. It's faster to open, has more guitar-specific tuning presets, no ads in the free tier, and Pro is $9.99/year vs $49.99/year for UG Pro." },
    ],
  },
  {
    slug: "n-track-tuner",
    name: "n-Track Tuner",
    shortName: "n-Track",
    appStoreRating: "4.4",
    annualPrice: "Free / $4.99 one-time",
    hasAds: true,
    freeAds: true,
    tuningCount: "Chromatic",
    bilingual: false,
    description: "n-Track Tuner is a chromatic tuner from the n-Track Studio team, known for its DAW software. It's a functional utility tuner with decent accuracy but shows ads in the free version and lacks guitar-specific presets.",
    mainComplaint: "Ads in free version, no guitar-specific tuning presets, basic UI with no string selector or alternate tuning library.",
    gtAdvantage: "GuitarTune is guitar-specific with named presets, a string selector, and an ad-free free tier. n-Track Tuner requires a paid upgrade ($4.99) to remove ads; GuitarTune's core tuner is always ad-free.",
    faqs: [
      { q: "Is n-Track Tuner any good?", a: "n-Track Tuner is a functional chromatic tuner but lacks guitar-specific features like tuning presets and string selectors. GuitarTune is built specifically for guitarists with 10 named tunings and an ad-free free tier." },
    ],
  },
];

export const TUNINGS: Tuning[] = [
  {
    slug: "standard",
    name: "Standard Tuning",
    shorthand: "EADGBE",
    strings: ["E2", "A2", "D3", "G3", "B3", "E4"],
    notes: ["E", "A", "D", "G", "B", "E"],
    genre: "All genres",
    difficulty: "Beginner",
    description: "Standard tuning (EADGBE) is the default tuning for 6-string guitar and the foundation of virtually all guitar instruction. From low to high, the strings are tuned to E, A, D, G, B, and E. The intervals between strings are mostly fourths (with a major third between G and B), creating a comfortable range for chords and scales.",
    howTo: [
      "Start with the low E string (thickest). It should sound like the lowest E note.",
      "Tune the A string: press the low E string at fret 5 — it should match the open A string.",
      "Tune the D string: press the A string at fret 5 — match to open D string.",
      "Tune the G string: press the D string at fret 5 — match to open G string.",
      "Tune the B string: press the G string at fret 4 (not 5) — match to open B string.",
      "Tune the high E string: press the B string at fret 5 — match to open high E string.",
      "Or use GuitarTune: open the app, select Standard, pluck each string, and follow the dial.",
    ],
    commonSongs: ["Wonderwall (Oasis)", "Hotel California (Eagles)", "Smoke on the Water (Deep Purple)", "Sweet Home Alabama (Lynyrd Skynyrd)"],
    isPremium: false,
    faqs: [
      { q: "What is standard guitar tuning?", a: "Standard guitar tuning is EADGBE — from the thickest (lowest) string to the thinnest (highest): E2, A2, D3, G3, B3, E4. It's the default tuning for 6-string electric and acoustic guitar." },
      { q: "How do I tune my guitar to standard tuning?", a: "Use a chromatic tuner app like GuitarTune. Open the app, select Standard tuning, pluck each string, and follow the dial until each string shows green (in tune). Start from the low E and work up to the high E." },
      { q: "Why is standard tuning EADGBE?", a: "Standard tuning evolved from lute and guitar traditions, designed to minimize hand movement for the most common chord shapes and scales. The interval pattern (mostly perfect fourths with one major third between G and B) makes it versatile for both chords and lead playing." },
    ],
  },
  {
    slug: "drop-d",
    name: "Drop D Tuning",
    shorthand: "DADGBE",
    strings: ["D2", "A2", "D3", "G3", "B3", "E4"],
    notes: ["D", "A", "D", "G", "B", "E"],
    genre: "Rock, Metal, Blues",
    difficulty: "Beginner",
    description: "Drop D tuning lowers the low E string one full step down to D, creating a D-A-D-G-B-E tuning. It's the most popular alternate tuning in rock and metal because it enables powerful one-finger power chords on the lowest three strings and adds a heavier, deeper sound to the guitar.",
    howTo: [
      "Start from standard EADGBE tuning.",
      "Only the low E string (thickest) needs to change — drop it down one full step to D.",
      "Reference: the low E string in Drop D should sound the same as the open D string (two strings up) — just an octave lower.",
      "In GuitarTune Pro: select 'Drop D' from the tuning menu, pluck the low E string, and follow the dial down until it reads D (green).",
      "The other 5 strings stay the same as standard tuning.",
    ],
    commonSongs: ["Killing in the Name (Rage Against the Machine)", "Everlong (Foo Fighters)", "Heart-Shaped Box (Nirvana)", "Black Hole Sun (Soundgarden)", "Moby Dick (Led Zeppelin)"],
    isPremium: true,
    faqs: [
      { q: "What is Drop D tuning?", a: "Drop D tuning (DADGBE) lowers the thickest guitar string from E down to D. The other five strings stay in standard tuning. Drop D makes power chords easier and gives the guitar a heavier, deeper sound." },
      { q: "How do I tune to Drop D?", a: "Start in standard tuning. Only the low E string changes — tune it down one whole step to D. You can match it to the open D string (one octave higher) or use GuitarTune Pro's Drop D preset for automatic detection." },
      { q: "What songs use Drop D tuning?", a: "Many rock and metal songs use Drop D: 'Everlong' by Foo Fighters, 'Killing in the Name' by Rage Against the Machine, 'Heart-Shaped Box' by Nirvana, and 'Moby Dick' by Led Zeppelin are all played in Drop D." },
      { q: "Is Drop D the same as open D?", a: "No. Drop D (DADGBE) only lowers the low E string to D — the rest stay in standard. Open D (DADF#AD) retunes all strings to form a D major chord when played open. They sound very different." },
    ],
  },
  {
    slug: "open-g",
    name: "Open G Tuning",
    shorthand: "DGDGBD",
    strings: ["D2", "G2", "D3", "G3", "B3", "D4"],
    notes: ["D", "G", "D", "G", "B", "D"],
    genre: "Blues, Slide, Country, Rock",
    difficulty: "Intermediate",
    description: "Open G tuning (DGDGBD) forms a G major chord when all strings are played open. It's the quintessential tuning for slide guitar and blues, and has been used on some of the most iconic rock recordings in history. Keith Richards of The Rolling Stones famously uses Open G tuning — with the low D string removed — for rhythm guitar parts.",
    howTo: [
      "Start from standard EADGBE tuning.",
      "Lower string 6 (low E) from E down to D — one whole step down.",
      "Leave string 5 (A) unchanged.",
      "Leave string 4 (D) unchanged.",
      "Leave string 3 (G) unchanged.",
      "Leave string 2 (B) unchanged.",
      "Lower string 1 (high E) from E down to D — one whole step down.",
      "Result: D-G-D-G-B-D. Use GuitarTune Pro's Open G preset for automatic tuning guidance.",
    ],
    commonSongs: ["Brown Sugar (Rolling Stones)", "Honky Tonk Women (Rolling Stones)", "Little Wing (Jimi Hendrix)", "Prodigal Son (Robert Johnson)", "Start Me Up (Rolling Stones)"],
    isPremium: true,
    faqs: [
      { q: "What is Open G tuning?", a: "Open G tuning (DGDGBD) is an alternate guitar tuning where strumming all open strings produces a G major chord. It's popular for slide guitar, blues, and was Keith Richards' tuning of choice for many Rolling Stones songs." },
      { q: "How do I tune to Open G?", a: "From standard tuning, lower strings 6 (low E→D) and 1 (high E→D) by one whole step each. Leave strings 5, 4, 3, and 2 unchanged. The result is D-G-D-G-B-D. Use GuitarTune Pro's Open G preset for automatic detection." },
      { q: "Is Open G good for beginners?", a: "Open G is approachable for intermediate players. Chords become simpler (major chords are just a barre), but the retuning changes familiar chord shapes. It's especially rewarding for slide guitar and blues." },
      { q: "What's the difference between Open G and Open D?", a: "Open G (DGDGBD) forms a G major chord open. Open D (DADF#AD) forms a D major chord open. Open G is more commonly used in rock and blues; Open D is popular in folk, Delta blues, and acoustic slide playing." },
    ],
  },
  {
    slug: "dadgad",
    name: "DADGAD Tuning",
    shorthand: "DADGAD",
    strings: ["D2", "A2", "D3", "G3", "A3", "D4"],
    notes: ["D", "A", "D", "G", "A", "D"],
    genre: "Folk, Celtic, Fingerpicking, World Music",
    difficulty: "Intermediate",
    description: "DADGAD tuning (D-A-D-G-A-D) creates an ambiguous, modal sound — neither major nor minor — that's ideal for Celtic music, folk fingerpicking, and atmospheric compositions. It was developed by guitarist Davy Graham in the 1960s after hearing Moroccan music, and has since become a cornerstone of Celtic and acoustic guitar playing.",
    howTo: [
      "Start from standard EADGBE tuning.",
      "Lower the low E string (string 6) from E to D — one whole step down.",
      "Leave the A string (string 5) unchanged.",
      "Leave the D string (string 4) unchanged.",
      "Leave the G string (string 3) unchanged.",
      "Lower the B string (string 2) from B to A — one whole step down.",
      "Lower the high E string (string 1) from E to D — one whole step down.",
      "Result: D-A-D-G-A-D. Use GuitarTune Pro's DADGAD preset for automatic guidance.",
    ],
    commonSongs: ["Kashmir (Led Zeppelin)", "Bron-Y-Aur Stomp (Led Zeppelin)", "Black Mountain Side (Led Zeppelin)", "The Galway Girl (traditional Irish)", "Various Celtic and Irish folk tunes"],
    isPremium: true,
    faqs: [
      { q: "What is DADGAD tuning?", a: "DADGAD is an alternate guitar tuning (D-A-D-G-A-D) that creates a suspended, modal sound commonly used in Celtic, folk, and world music. Strumming open strings creates a Dsus4 chord." },
      { q: "What songs use DADGAD tuning?", a: "Led Zeppelin's 'Kashmir' and 'Bron-Y-Aur Stomp' are famously played in DADGAD (or variations close to it). It's also widely used in Celtic, Irish, and Scottish folk music." },
      { q: "How do I tune to DADGAD?", a: "From standard tuning, lower strings 6, 2, and 1 by one whole step each (E→D for strings 6 and 1, B→A for string 2). Strings 5, 4, and 3 stay unchanged. Use GuitarTune Pro's DADGAD preset for automatic detection." },
      { q: "Is DADGAD hard to learn?", a: "DADGAD requires relearning chord shapes since the familiar positions all change. However, the tuning is very guitar-friendly for fingerpicking patterns and pentatonic riffs. Most intermediate guitarists can get comfortable within a few weeks of practice." },
    ],
  },
  {
    slug: "open-d",
    name: "Open D Tuning",
    shorthand: "DADF#AD",
    strings: ["D2", "A2", "D3", "F#3", "A3", "D4"],
    notes: ["D", "A", "D", "F#", "A", "D"],
    genre: "Blues, Folk, Slide Guitar, Acoustic",
    difficulty: "Intermediate",
    description: "Open D tuning (DADF#AD) forms a D major chord when all strings are played open. It's one of the oldest alternate tunings and a favorite for Delta blues slide guitar. The lower tension and resonant D major voicing make it ideal for bottleneck slide playing and acoustic fingerpicking.",
    howTo: [
      "Start from standard EADGBE tuning.",
      "Lower the low E string (string 6) from E to D (one whole step).",
      "Leave the A string (string 5) unchanged.",
      "Leave the D string (string 4) unchanged.",
      "Lower the G string (string 3) from G to F# (one half step).",
      "Lower the B string (string 2) from B to A (one whole step).",
      "Lower the high E string (string 1) from E to D (one whole step).",
      "Result: D-A-D-F#-A-D. Use GuitarTune Pro's Open D preset.",
    ],
    commonSongs: ["The Sky Is Crying (Elmore James)", "Slide guitar blues standards", "Big Yellow Taxi (Joni Mitchell)", "Sonny Boy Williamson — various tracks"],
    isPremium: true,
    faqs: [
      { q: "What is Open D tuning?", a: "Open D tuning (DADF#AD) tunes the guitar so that strumming all open strings produces a D major chord. It's popular for slide guitar, Delta blues, and acoustic fingerpicking." },
      { q: "How do I tune to Open D?", a: "From standard tuning, lower strings 6, 3, 2, and 1 (while keeping strings 5 and 4 the same). String 6: E→D, String 3: G→F#, String 2: B→A, String 1: E→D. Use GuitarTune Pro's Open D preset." },
      { q: "What's the difference between Open D and Open G?", a: "Open D (DADF#AD) produces a D major chord open and is common in Delta blues and folk. Open G (DGDGBD) produces a G major chord and is more common in rock and classic blues. Both are used for slide guitar." },
    ],
  },
  {
    slug: "open-e",
    name: "Open E Tuning",
    shorthand: "EBE G#BE",
    strings: ["E2", "B2", "E3", "G#3", "B3", "E4"],
    notes: ["E", "B", "E", "G#", "B", "E"],
    genre: "Blues, Slide Guitar, Rock",
    difficulty: "Intermediate",
    description: "Open E tuning (EBEG#BE) tunes the guitar to form an E major chord when all strings are played open. It's particularly popular for slide guitar and is associated with legends like Duane Allman and Derek Trucks. Unlike Open D, which tunes down, Open E requires tuning three strings up — which increases string tension. Many players use lighter strings with Open E.",
    howTo: [
      "Start from standard EADGBE tuning.",
      "Leave the low E string (string 6) unchanged.",
      "Tune the A string (string 5) up from A to B (one whole step up).",
      "Tune the D string (string 4) up from D to E (one whole step up).",
      "Tune the G string (string 3) up from G to G# (one half step up).",
      "Leave the B string (string 2) unchanged.",
      "Leave the high E string (string 1) unchanged.",
      "Note: Tuning up increases string tension — use lighter gauge strings to avoid damage.",
      "Use GuitarTune Pro's Open E preset for automatic guidance.",
    ],
    commonSongs: ["Statesboro Blues (Allman Brothers)", "Midnight Rider (Allman Brothers)", "Jumpin' Jack Flash (Rolling Stones)", "Derek Trucks Band — various recordings"],
    isPremium: true,
    faqs: [
      { q: "What is Open E tuning?", a: "Open E tuning (EBEG#BE) tunes the guitar to form an E major chord when all strings are strummed open. It's popular for slide guitar and closely associated with Duane Allman." },
      { q: "Is Open E hard on guitar strings?", a: "Yes. Open E requires tuning three strings up from standard, which increases tension. Many guitarists recommend using a lighter string gauge (10s instead of 11s) when playing in Open E to reduce stress on the neck and strings." },
      { q: "What's the difference between Open E and Open D?", a: "Open E forms an E major chord open; Open D forms a D major chord. Open E is tuned up (higher tension), while Open D is tuned down (lower tension). Both are used for slide guitar, but Open D is considered easier on the guitar." },
    ],
  },
  {
    slug: "drop-c",
    name: "Drop C Tuning",
    shorthand: "CADGBE (low C)",
    strings: ["C2", "G2", "C3", "F3", "A3", "D4"],
    notes: ["C", "G", "C", "F", "A", "D"],
    genre: "Metal, Heavy Rock, Hardcore",
    difficulty: "Intermediate",
    description: "Drop C tuning takes Drop D and shifts everything down one additional whole step, resulting in a C-G-C-F-A-D tuning. It delivers an extremely heavy, low-end sound favored in metal, metalcore, and heavy rock. Like Drop D, it allows one-finger power chords on the lowest three strings, now at an even lower pitch.",
    howTo: [
      "Method 1 (from standard): Tune all strings down one whole step to D-G-C-F-A-D, then drop the low D string down one more step to C.",
      "Method 2 (from Drop D): Lower every string by one whole step — low D becomes C, A becomes G, D becomes C, G becomes F, B becomes A, high E becomes D.",
      "Result: C-G-C-F-A-D. The guitar will feel much looser — heavier strings (11s or 12s) are recommended.",
      "Use GuitarTune Pro's Drop C preset for automatic detection.",
    ],
    commonSongs: ["Chop Suey (System of a Down)", "Down with the Sickness (Disturbed)", "Numb (Linkin Park)", "B.Y.O.B. (System of a Down)"],
    isPremium: true,
    faqs: [
      { q: "What is Drop C tuning?", a: "Drop C tuning (CGCFAD) lowers all guitar strings by one whole step from Drop D tuning. It creates a heavier, lower sound popular in metal and heavy rock. The low C string allows powerful one-finger power chords." },
      { q: "How do I tune to Drop C?", a: "Start from Drop D tuning (DADGBE), then lower every string by one additional whole step. The result is C-G-C-F-A-D. Use GuitarTune Pro's Drop C preset for automatic detection." },
      { q: "What gauge strings should I use for Drop C?", a: "For Drop C, heavier gauge strings (0.011–0.054 or 0.012–0.056) are recommended to maintain playable tension at the lower pitch. Standard 0.009s or 0.010s will be too loose and floppy in Drop C." },
    ],
  },
  {
    slug: "double-drop-d",
    name: "Double Drop D Tuning",
    shorthand: "DADGBD",
    strings: ["D2", "A2", "D3", "G3", "B3", "D4"],
    notes: ["D", "A", "D", "G", "B", "D"],
    genre: "Folk, Rock, Blues",
    difficulty: "Beginner",
    description: "Double Drop D tunes both the low and high E strings down to D, resulting in D-A-D-G-B-D. It retains the familiar feel of standard tuning while adding D-chord resonance to both ends of the guitar. Neil Young is the most notable user of Double Drop D, giving his acoustic playing its distinctive droning quality.",
    howTo: [
      "Start from standard EADGBE tuning.",
      "Lower the low E string (string 6) from E to D — one whole step down.",
      "Leave strings 5, 4, 3, and 2 unchanged.",
      "Lower the high E string (string 1) from E to D — one whole step down.",
      "Result: D-A-D-G-B-D. This is a free tuning in GuitarTune.",
    ],
    commonSongs: ["Cinnamon Girl (Neil Young)", "Ohio (CSNY)", "Down by the River (Neil Young)", "The Needle and the Damage Done (Neil Young)"],
    isPremium: false,
    faqs: [
      { q: "What is Double Drop D tuning?", a: "Double Drop D (DADGBD) lowers both the low and high E strings from E to D. It's closely associated with Neil Young and creates a droning, resonant quality for acoustic and electric guitar." },
      { q: "How is Double Drop D different from Drop D?", a: "Drop D (DADGBE) only lowers the low E string. Double Drop D (DADGBD) also lowers the high E string to D. Both share the same low D; Double Drop D adds D resonance on the top string as well." },
    ],
  },
  {
    slug: "open-c",
    name: "Open C Tuning",
    shorthand: "CGCGCE",
    strings: ["C2", "G2", "C3", "G3", "C4", "E4"],
    notes: ["C", "G", "C", "G", "C", "E"],
    genre: "Folk, Fingerpicking, Alternative",
    difficulty: "Intermediate",
    description: "Open C tuning (CGCGCE) forms a C major chord when all strings are played open. It's popular for fingerpicking and acoustic guitar because of its warm, resonant sound and the ease of playing suspended and add9 chords. The tuning creates an especially rich, piano-like sound for solo acoustic pieces.",
    howTo: [
      "Start from standard EADGBE tuning.",
      "Lower string 6 (low E) from E to C — a minor third down (three half steps).",
      "Lower string 5 (A) from A to G — one whole step down.",
      "Lower string 4 (D) from D to C — one whole step down.",
      "Leave string 3 (G) unchanged.",
      "Raise string 2 (B) from B to C — one half step up.",
      "Leave string 1 (high E) unchanged.",
      "Result: C-G-C-G-C-E. Use GuitarTune's free Open C preset for automatic guidance.",
    ],
    commonSongs: ["Friends (Led Zeppelin)", "Bron-Y-Aur (Led Zeppelin)", "Many John Fahey acoustic pieces", "Various folk and fingerpicking compositions"],
    isPremium: false,
    faqs: [
      { q: "What is Open C tuning?", a: "Open C tuning (CGCGCE) tunes the guitar so that all open strings form a C major chord. It's popular for acoustic fingerpicking and creates a warm, rich sound especially suited to solo guitar pieces." },
      { q: "How do I tune to Open C?", a: "From standard, lower strings 6 (E→C), 5 (A→G), and 4 (D→C), raise string 2 (B→C), and leave strings 3 and 1 unchanged. Use GuitarTune's free Open C preset for automatic guidance." },
    ],
  },
  {
    slug: "all-fourths",
    name: "All Fourths Tuning",
    shorthand: "EADGCF",
    strings: ["E2", "A2", "D3", "G3", "C4", "F4"],
    notes: ["E", "A", "D", "G", "C", "F"],
    genre: "Jazz, Progressive, Music Theory",
    difficulty: "Advanced",
    description: "All Fourths tuning (EADGCF) extends the standard tuning pattern — which is mostly fourths — to be perfectly consistent across all six strings. The only change from standard is raising the B string to C and the high E string to F. This creates a logically consistent pattern where all chord shapes and scale patterns are symmetrical across every string pair, making it highly valued by music theorists and jazz guitarists.",
    howTo: [
      "Start from standard EADGBE tuning.",
      "Leave strings 6, 5, 4, and 3 unchanged (E-A-D-G).",
      "Raise string 2 (B) up from B to C — one half step up.",
      "Raise string 1 (high E) from E up to F — one half step up.",
      "Result: E-A-D-G-C-F. All intervals between adjacent strings are now perfect fourths.",
      "Use GuitarTune's free All Fourths preset.",
    ],
    commonSongs: ["Used by Robert Fripp (King Crimson)", "Used by Stanley Jordan for jazz", "Common in progressive and avant-garde guitar"],
    isPremium: false,
    faqs: [
      { q: "What is All Fourths tuning?", a: "All Fourths tuning (EADGCF) makes every string-to-string interval a perfect fourth, unlike standard tuning which has a major third between G and B. This makes chord shapes and scales symmetrical across all string pairs." },
      { q: "Who plays in All Fourths tuning?", a: "Robert Fripp of King Crimson and Stanley Jordan have both used All Fourths tuning. It's also popular among musicians with a strong theory background who want consistent patterns across the fretboard." },
      { q: "Is All Fourths tuning good for beginners?", a: "All Fourths is more advanced — standard chord shapes don't transfer, requiring you to relearn most shapes. It's rewarding for theoretically-oriented players but not ideal for beginners starting out." },
    ],
  },
  {
    slug: "drop-b",
    name: "Drop B Tuning",
    shorthand: "BF#BEG#C#",
    strings: ["B1", "F#2", "B2", "E3", "G#3", "C#4"],
    notes: ["B", "F#", "B", "E", "G#", "C#"],
    genre: "Metal, Djent, Progressive Metal",
    difficulty: "Advanced",
    description: "Drop B tuning (B-F#-B-E-G#-C#) drops all strings down one and a half steps from standard, then drops the low string an additional step to B. It produces an extremely heavy, ultra-low sound used in modern metal, djent, and progressive metal. Bands like Slipknot and Bullet for My Valentine have used Drop B for its crushing low end.",
    howTo: [
      "Method 1 — from Drop C tuning: Lower every string by one additional half step.",
      "Drop C is C-G-C-F-A-D. Lowering each string one half step gives B-F#-B-E-G#-C#.",
      "Method 2 — from standard: Lower all strings three half steps (one and a half steps), then lower string 6 one additional half step.",
      "Result: B-F#-B-E-G#-C#. Use very heavy strings (12–56 or 13–62) — standard gauge strings will feel unplayably loose.",
      "GuitarTune Pro's chromatic dial can guide you for Drop B tuning.",
    ],
    commonSongs: ["Psychosocial (Slipknot)", "Hand of Blood (Bullet for My Valentine)", "Various Architects songs", "Modern metalcore and djent compositions"],
    isPremium: true,
    faqs: [
      { q: "What is Drop B tuning?", a: "Drop B tuning (BF#BEG#C#) lowers all strings one and a half steps from standard, then drops the low string an additional step to B. It creates an extremely heavy, low sound used in modern metal and djent." },
      { q: "What strings should I use for Drop B?", a: "Drop B requires heavy gauge strings — at minimum 0.012–0.056, ideally 0.013–0.062. Standard 10s or 11s will be unplayably floppy. Many players use a dedicated guitar setup for Drop B." },
      { q: "What bands play in Drop B?", a: "Slipknot have used Drop B on tracks like 'Psychosocial.' Bullet for My Valentine and various metalcore and djent artists also use Drop B for its ultra-heavy low end." },
    ],
  },
  {
    slug: "open-a",
    name: "Open A Tuning",
    shorthand: "EAE A C#E",
    strings: ["E2", "A2", "E3", "A3", "C#4", "E4"],
    notes: ["E", "A", "E", "A", "C#", "E"],
    genre: "Blues, Slide Guitar, Country",
    difficulty: "Intermediate",
    description: "Open A tuning (E-A-E-A-C#-E) forms an A major chord when all strings are played open. It's closely related to Open G — essentially the same chord shape shifted up a whole step — and is widely used for slide guitar and Delta blues. The tuning is particularly effective for bottleneck playing in the key of A, which is central to the blues tradition.",
    howTo: [
      "Start from standard EADGBE tuning.",
      "Leave string 6 (low E) unchanged.",
      "Leave string 5 (A) unchanged.",
      "Raise string 4 (D) from D to E — one whole step up.",
      "Raise string 3 (G) from G to A — one whole step up.",
      "Raise string 2 (B) from B to C# — one whole step up.",
      "Leave string 1 (high E) unchanged.",
      "Result: E-A-E-A-C#-E. Increased tension on strings 4, 3, and 2 — consider lighter gauges.",
    ],
    commonSongs: ["Dust My Broom (Elmore James)", "Open A blues standards", "Country slide guitar", "Various Robert Johnson-influenced recordings"],
    isPremium: true,
    faqs: [
      { q: "What is Open A tuning?", a: "Open A tuning (EAEAC#E) tunes the guitar so all open strings form an A major chord. It's popular for slide guitar and blues in the key of A, closely related to Open G tuning shifted up one step." },
      { q: "Is Open A the same as Open G?", a: "Open A and Open G produce the same major chord voicing on all open strings, but in different keys. Open A (EAEAC#E) is one whole step higher than Open G (DGDGBD). Both are used for slide guitar." },
      { q: "How do I tune to Open A?", a: "From standard, raise strings 4, 3, and 2 each by one whole step (D→E, G→A, B→C#). Leave strings 6, 5, and 1 unchanged. Use lighter gauge strings to handle the increased tension." },
    ],
  },
  {
    slug: "half-step-down",
    name: "Half Step Down (Eb)",
    shorthand: "Eb Ab Db Gb Bb Eb",
    strings: ["Eb2", "Ab2", "Db3", "Gb3", "Bb3", "Eb4"],
    notes: ["Eb", "Ab", "Db", "Gb", "Bb", "Eb"],
    genre: "Rock, Blues, Classical, All Genres",
    difficulty: "Beginner",
    description: "Half step down tuning lowers all six strings by one half step from standard, resulting in Eb-Ab-Db-Gb-Bb-Eb (also written as D#-G#-C#-F#-A#-D#). It's one of the most common alternate tunings in rock, used extensively by Jimi Hendrix, Slash, and Stevie Ray Vaughan. The slightly lower pitch is easier to sing over for many vocalists and reduces string tension for easier bending.",
    howTo: [
      "Start from standard EADGBE tuning.",
      "Lower every string by one half step: E→Eb, A→Ab, D→Db, G→Gb, B→Bb, E→Eb.",
      "All strings move down by the same amount — the chord shapes and scale patterns stay identical to standard.",
      "In GuitarTune Pro, select the Eb/Half Step Down preset and pluck each string to follow the dial.",
      "The guitar will feel slightly looser — string bending becomes easier.",
    ],
    commonSongs: ["Purple Haze (Jimi Hendrix)", "November Rain (Guns N' Roses)", "Pride and Joy (Stevie Ray Vaughan)", "Cult of Personality (Living Colour)", "Black Magic Woman (Santana)"],
    isPremium: true,
    faqs: [
      { q: "What is half step down tuning?", a: "Half step down tuning lowers all guitar strings by one half step from standard, resulting in Eb-Ab-Db-Gb-Bb-Eb. Chord shapes and scale patterns are identical to standard tuning — everything just sounds a half step lower." },
      { q: "Why do guitarists tune half a step down?", a: "Common reasons: easier string bending (lower tension), matching a vocalist's key, matching the sound of classic recordings (Hendrix, SRV, Guns N' Roses), or personal preference for the slightly darker tone." },
      { q: "What famous songs are in half step down tuning?", a: "Jimi Hendrix's 'Purple Haze,' Stevie Ray Vaughan's 'Pride and Joy,' Guns N' Roses' 'November Rain,' and many other rock classics are recorded in Eb/half step down tuning." },
    ],
  },
  {
    slug: "whole-step-down",
    name: "Whole Step Down (D)",
    shorthand: "D G C F A D",
    strings: ["D2", "G2", "C3", "F3", "A3", "D4"],
    notes: ["D", "G", "C", "F", "A", "D"],
    genre: "Rock, Metal, Grunge, Alternative",
    difficulty: "Beginner",
    description: "Whole step down tuning (D-G-C-F-A-D) lowers all six strings by one full step from standard. Like half step down, the chord shapes and scale patterns are identical to standard tuning — everything sounds a whole step lower. It delivers a heavier, darker tone than standard and was a signature sound of grunge and early 2000s hard rock. Kurt Cobain, Alice in Chains, and many other artists recorded in this tuning.",
    howTo: [
      "Start from standard EADGBE tuning.",
      "Lower every string by one whole step: E→D, A→G, D→C, G→F, B→A, E→D.",
      "All shapes remain the same as standard tuning — a G chord shape produces an F chord, a C shape produces a Bb chord, etc.",
      "Use GuitarTune Pro's Whole Step Down preset for automatic detection.",
      "Heavier strings (11s or 12s) are recommended to maintain comfortable tension.",
    ],
    commonSongs: ["In Bloom (Nirvana)", "Would? (Alice in Chains)", "Sad But True (Metallica — variations)", "Come as You Are (Nirvana)"],
    isPremium: true,
    faqs: [
      { q: "What is whole step down tuning?", a: "Whole step down tuning (DGCFAD) lowers all strings by one full step from standard. The result is a heavier, darker tone with the same chord and scale shapes as standard — just sounding one step lower." },
      { q: "What's the difference between Drop D and whole step down?", a: "Drop D only lowers the low E string to D. Whole step down lowers all six strings to D-G-C-F-A-D. In whole step down, the relationship between strings is identical to standard tuning; in Drop D, only the lowest string changes." },
      { q: "What bands use whole step down tuning?", a: "Nirvana used whole step down on several songs. Alice in Chains, early Metallica, and many grunge and alternative bands used it for a heavier, lower sound while keeping standard chord shapes." },
    ],
  },
  {
    slug: "nashville",
    name: "Nashville Tuning",
    shorthand: "E A D G B E (high strung)",
    strings: ["E3", "A3", "D4", "G3", "B3", "E4"],
    notes: ["E", "A", "D", "G", "B", "E"],
    genre: "Country, Pop, Studio Recording",
    difficulty: "Intermediate",
    description: "Nashville tuning (also called high-strung tuning) uses the same note names as standard tuning (EADGBE) but replaces the four lowest strings with lighter-gauge strings tuned one octave higher. The G, B, and high E strings stay the same. This creates a bright, shimmering, 12-string-like quality and is widely used in Nashville recording studios to layer with a standard-tuned guitar for a rich, full sound.",
    howTo: [
      "You need a special string set — use the octave strings from a 12-string guitar set (the thinner string from each pair) for strings 6, 5, 4, and 3.",
      "Tune string 6 to E3 (one octave above standard low E).",
      "Tune string 5 to A3 (one octave above standard A).",
      "Tune string 4 to D4 (one octave above standard D).",
      "Leave string 3 (G3), string 2 (B3), and string 1 (E4) at their standard pitches.",
      "Result: E3-A3-D4-G3-B3-E4. The note names match standard tuning but the low strings sound an octave higher.",
    ],
    commonSongs: ["Used on countless Nashville country recordings", "Dust in the Wind (Kansas — layered with standard)", "Wild Horses (Rolling Stones — studio layering)", "Common in modern pop and indie production"],
    isPremium: true,
    faqs: [
      { q: "What is Nashville tuning?", a: "Nashville tuning (high-strung tuning) uses the same note names as standard EADGBE, but strings 6, 5, 4, and 3 are replaced with thinner strings tuned one octave higher. It creates a bright, chimey quality often used in studio recording." },
      { q: "Can I use regular strings for Nashville tuning?", a: "No. Regular strings tuned up an octave would break. You need the octave (thinner) strings from a 12-string set for the bottom four strings. The top two strings (B and high E) use standard strings." },
      { q: "Why is it called Nashville tuning?", a: "It's named after Nashville, Tennessee, where session guitarists commonly use it as a layering technique in recordings. A Nashville-tuned guitar played alongside a standard-tuned guitar creates a rich, 12-string-like sound without actually playing a 12-string." },
    ],
  },
];
